get:
  tags:
    - Accounts
  summary: Get all the account configrmations
  description: Get all the account configrmations
  produces:
    - application/json
  parameters:
    - in: path
      name: accountId
      required: true
      schema:
        type: string
        format: uuid
  responses:
    allOf:
      - $ref: ../global/defaultResponsesDefinition.yml
      - 200:
          description: array of account configs
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
                    allOf:
                      - $ref: ../global/paginatedResponseDefinition.yml
                      - type: object
                        properties:
                          items:
                            type: array
                            items:
                              type: object
                              allOf:
                                - $ref: ../global/autoGeneratedDataDefinition.yml
                                - $ref: ./accountAccountConfigDefinition.yml
              example:
                - _id: c54a858a-b095-4405-9a1c-8567ec91da5e
                  key: fullname
                  value: Gilbert D. Cuerbo
                  type: string
                  createdAt: 2023-08-27T14:51:58.619Z
                  updatedAt: 2023-08-27T14:51:58.619Z
post:
  tags:
    - Accounts
  summary: Create a account config into account data
  description: Create a account config into account data
  produces:
    - application/json
  parameters:
    - in: path
      name: accountId
      required: true
      schema:
        type: string
        format: uuid
  requestBody:
    content:
      application/x-www-form-urlencoded:
        schema:
          type: object
          required:
            - key
            - value
            - type
          properties:
            key:
              type: string
            value:
              type: string
            type:
              type: string
              enum: [string, number, date, boolean]
  responses:
    allOf:
      - $ref: ../global/defaultResponsesDefinition.yml
      - 200:
          description: Successfull account config creation
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - $ref: ../global/autoGeneratedDataDefinition.yml
                  - $ref: ./accountAccountConfigDefinition.yml
              example:
                _id: c54a858a-b095-4405-9a1c-8567ec91da5e
                key: fullname
                value: Gilbert D. Cuerbo
                type: string
                createdAt: 2023-08-27T14:51:58.619Z
                updatedAt: 2023-08-27T14:51:58.619Z