swagger: '2.0'
info:
  version: 1.0.0
  title: API documenations using Swagger
  description: Sample project which generates API documentaion using swagger.
  contact:
    name: Gilbert D. Cuerbo
    email: gilbert.cuerbo@gmail.com
  license:
    name: MIT
    url: https://github.com/gilbertgit95/kagiweb-api-core-a/blob/master/LICENSE
schemes: [http, https]
host: localhost:3000
basePath: /api/v1/
tags: 
  $ref: ./tags.yml
paths:
  $ref: ./paths/index.yml
definitions:
  $ref: ./definitions/index.yml