const router = require('express').Router();

const {
    getMultipleAccounts,
    createMultipleAccounts,
    updateMultipleAccounts,
    deleteMultipleAccounts
} = require('./multipleAccounts');

const {
    getAccount,
    createAccount,
    updateAccount,
    deleteAccount
} = require('./singleAccount');

/**
 * @swagger
 * components:
 *      schemas:
 *          Account:
 *              type: object
 *              required:
 *                  - username
 *                  - roleId
 *              properties:
 *                  id:
 *                      type: string
 *                      description: autogenerated value
 *                  username:
 *                      type: string
 *                      description: account username
 *                  roleId:
 *                      type: string
 *                      description: account role id
 *                  twoFactorAuth:
 *                      type: boolean
 *                      description: two factor authentication
 *                  disableAccount:
 *                      type: boolean
 *                      description: account disable status
 *                  primaryEmail:
 *                      type: string
 *                      description: primary account email
 *                  secondayEmail:
 *                      type: string
 *                      description: secondary account email
 *                  primaryEmailVerified:
 *                      type: string
 *                      description: primary email verified status
 *                  secondaryEmailVerified:
 *                      type: string
 *                      description: secondary email verified status
 *                  primaryNumber:
 *                      type: string
 *                      description: primary contact number
 *                  secondayNumber:
 *                      type: string
 *                      description: secondary contact number
 *                  primaryNumberVerified:
 *                      type: string
 *                      description: primary contact verified status
 *                  secondaryNumberVerified:
 *                      type: string
 *                      description: secondary contact verified status
 *                  resetPasswordAttempt:
 *                      type: string
 *                      description: reset password attempt count
 *                  loginAccountAttempt:
 *                      type: string
 *                      description: login account attemp count
 *                  createdAt:
 *                      type: string
 *                      description: date when this item was created
 *                  updatedAt:
 *                      type: string
 *                      description: date when this item was updated
 *              example:
 *                  id: e79c8692-4cc2-4971-a52c-832e87b28e8f
 *                  username: master
 *                  twoFactorAuth: false
 *                  disableAccount: false
 *                  primaryEmail: null
 *                  secondayEmail: null
 *                  primaryEmailVerified: false
 *                  secondaryEmailVerified: false
 *                  primaryNumber: null
 *                  secondayNumber: null
 *                  primaryNumberVerified: false
 *                  secondaryNumberVerified: false
 *                  resetPasswordAttempt: 0
 *                  loginAccountAttempt: 0
 *                  createdAt: 2021-11-20T15:27:31.513Z
 *                  updatedAt: 2021-11-20T15:27:31.513Z
 *                  roleId: e79c8692-4cc2-4971-a52c-832e87b46e8f
 */

/**
 * @swagger
 * tags:
 *      name: Accounts
 *      description: Api to manage accounts
 */

/**
 * @swagger
 * /api/v1/accounts:
 *      get:
 *          tags: [Accounts]
 *          summary: returns list of accounts
 *          responses:
 *              200:
 *                  description: object containing list of accounts
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  data:
 *                                      type: object
 *                                      properties:
 *                                          next:
 *                                              type: string
 *                                              nullable: true
 *                                              description: url pointing to the next page
 *                                          pageSize:
 *                                              type: number
 *                                              description: number of items per page
 *                                          pageNumber:
 *                                              type: number
 *                                              description: the current page number
 *                                          totalPage:
 *                                              type: number
 *                                              description: all the availbale pages
 *                                          totalItems:
 *                                              type: number
 *                                              description: all items in all pages
 *                                          items:
 *                                              type: array
 *                                              items:
 *                                                  allOf:
 *                                                      - $ref: '#/components/schemas/Account'
 *                                                      - type: object
 *                                                        properties:
 *                                                          role:
 *                                                              $ref: '#/components/schemas/Role'
 *                                                          accountClaims:
 *                                                              type: array
 *                                                              items:
 *                                                                  $ref: '#/components/schemas/Role'
 *              500:
 *                  description: Some error occured in the server
 *                  content:
 *                      application/json:
 *                          schema:
 *                              $ref: '#/components/schemas/Error'
 */

router.get('/accounts', getMultipleAccounts)
router.post('/accounts', createMultipleAccounts)
router.put('/accounts', updateMultipleAccounts)
router.delete('/accounts', deleteMultipleAccounts)

router.get('/accounts/{id}', getAccount)
router.post('/accounts/new', createAccount)
router.put('/accounts/{id}', updateAccount)
router.delete('/accounts/{id}', deleteAccount)

module.exports = router