const router = require('express').Router();

const {
    getMultipleAccounts,
    createMultipleAccounts,
    updateMultipleAccounts,
    deleteMultipleAccounts
} = require('./multipleAccounts');

const {
    getAccount,
    createAccount,
    updateAccount,
    deleteAccount
} = require('./singleAccount');

/**
 * @swagger
 * components:
 *      schemas:
 *          Account:
 *              type: object
 *              required:
 *                  - username
 *                  - password
 *                  - roleId
 *              properties:
 *                  id:
 *                      type: string
 *                      description: autogenerated value
 *                  createdAt:
 *                      type: string
 *                      description: date when this item was created
 *                  updatedAt:
 *                      type: string
 *                      description: date when this item was updated
 *                  
 */
router.get('/accounts', getMultipleAccounts)
router.post('/accounts', createMultipleAccounts)
router.put('/accounts', updateMultipleAccounts)
router.delete('/accounts', deleteMultipleAccounts)

router.get('/accounts/{id}', getAccount)
router.post('/accounts/new', createAccount)
router.put('/accounts/{id}', updateAccount)
router.delete('/accounts/{id}', deleteAccount)

module.exports = router