get:
  tags:
    - Owner
  summary: Get all the Owner Workspace account refs configurations
  description: Get all the Owner Workspace account refs configurations
  produces:
    - application/json
  parameters:
    - in: path
      name: accountId
      required: true
      schema:
        type: string
        format: uuid
    - in: path
      name: workspaceId
      required: true
      schema:
        type: string
        format: uuid
    - in: path
      name: accountRefId
      required: true
      schema:
        type: string
        format: uuid
  responses:
    allOf:
      - $ref: ../global/defaultResponsesDefinition.yml
      - 200:
          description: array of Owner Workspace account refs configuration
          content:
            application/json:
              schema:
                type: array
                items:
                    type: object
                    allOf:
                      - $ref: ../global/paginatedResponseDefinition.yml
                      - type: object
                        properties:
                          items:
                            type: array
                            items:
                              type: object
                              allOf:
                                - $ref: ../global/autoGeneratedDataDefinition.yml
                                - $ref: ../accountWorkspaceAccountRefsAccountConfigs/accountWorkspaceAccountRefsAccountConfigDefinition.yml
              example:
                - _id: c54a858a-b095-4405-9a1c-8567ec91da5e
                  key: default-role
                  value: c54a858a-b095-4405-9a1c-8567ec91da5e
                  type: string
                  createdAt: 2023-08-27T14:51:58.619Z
                  updatedAt: 2023-08-27T14:51:58.619Z
