const router = require('express').Router();

const {
    getMultipleEndpoints,
    createMultipleEndpoints,
    updateMultipleEndpoints,
    deleteMultipleEndpoints
} = require('./multipleEndpoints');

const {
    getSingleEndpoint,
    createSingleEndpoint,
    updateSingleEndpoint,
    deleteSingleEndpoint
} = require('./singleEndpoint');

/**
 * @swagger
 * components:
 *      schemas:
 *          Endpoint:
 *              type: object
 *              required:
 *                  - endpoint
 *                  - type
 *                  - category
 *                  - subcategory
 *              properties:
 *                  uuid:
 *                      type: string
 *                      description: autogenerated value
 *                  endpoint:
 *                      type: string
 *                      description: the actual value that will be checked during access checking
 *                  type:
 *                      type: string
 *                      description: the type of endpoint
 *                  category:
 *                      type: string
 *                      description: the group where this type belong
 *                  subcategory:
 *                      type: string
 *                      description: the subgroup where this type and category belong
 *                  description:
 *                      type: string
 *                      description: discribes the endpoint
 *                  createdAt:
 *                      type: string
 *                      description: date when this item was created
 *                  updatedAt:
 *                      type: string
 *                      description: date when this item was updated
 *              example:
 *                  uuid: db422ca5-b0a0-43b1-9381-417be994f08e,
 *                  endpoint: /api/v1/endpoints/new,
 *                  type: server,
 *                  category: route,
 *                  subcategory: POST,
 *                  description: create a single endpoint,
 *                  createdAt: 2021-11-08T06:19:31.163Z,
 *                  updatedAt: 2021-11-08T08:11:11.815Z
 *      
 */

/**
 * @swagger
 * tags:
 *      name: Endpoints
 *      description: API to manage the endpoints
 */

// routes for handling batch data
/**
 * @swagger
 * /api/v1/endpoints:
 *      get:
 *          tags: [Endpoints]
 *          summary: Returns multiple endpoint in paginated manner
 *          parameters:
 *              - in: query
 *                name: pageSize
 *                schema:
 *                      type: number
 *                description: number of items per page 
 *              - in: query
 *                name: pageNumber
 *                schema:
 *                      type: number
 *                description: current page number
 *          responses:
 *              200:
 *                  description: object containing a list of endpoints
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  data:
 *                                      type: object
 *                                      properties:
 *                                          next:
 *                                              type: string
 *                                              nullable: true
 *                                              description: url pointing to the next page
 *                                          pageSize:
 *                                              type: number
 *                                              description: number of items per page
 *                                          pageNumber:
 *                                              type: number
 *                                              description: the current page number
 *                                          totalPage:
 *                                              type: number
 *                                              description: all the availbale pages
 *                                          totalItems:
 *                                              type: number
 *                                              description: all items in all pages
 *                                          items:
 *                                              type: array
 *                                              items:
 *                                                  $ref: '#/components/schemas/Endpoint'
 */
router.get('/endpoints', getMultipleEndpoints)
router.post('/endpoints', createMultipleEndpoints)
router.put('/endpoints', updateMultipleEndpoints)
router.delete('/endpoints', deleteMultipleEndpoints)

// routes for handling single data
/**
 * @swagger
 * /api/v1/endpoints/{uuid}:
 *      get:
 *          tags: [Endpoints]
 *          summary: Returns a single endpoint with uuid equivalent to url parameter
 *          parameters:
 *              - in: path
 *                name: uuid
 *                schema:
 *                      type: string
 *                required: true
 *                description: uuid of endpoint
 *          responses:
 *              200:
 *                  description: returns endpoint
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  data:
 *                                      $ref: '#/components/schemas/Endpoint'
 *              500:
 *                  description: Some error occured in the server
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  message:
 *                                      type: string
 *                                  defaultMessage:
 *                                      type: string
 *              404:
 *                  description: None existing data
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  message:
 *                                      type: string
 *                                  defaultMessage:
 *                                      type: string             
 */
router.get('/endpoints/:uuid', getSingleEndpoint)
router.post('/endpoints/new', createSingleEndpoint)
router.put('/endpoints/:uuid', updateSingleEndpoint)
router.delete('/endpoints/:uuid', deleteSingleEndpoint)

module.exports = router