get:
    tags:
      - Roles
    summary: Get all the Roles
    description: Get all the Roles
    produces:
      - application/json
    parameters:
      - in: query
        name: page
        schema:
          type: integer
      - in: query
        name: pageSize
        schema:
          type: integer
    responses:
      allOf:
        - $ref: ../global/defaultResponsesDefinition.yml
        - 200:
            description: array of roles
            content:
              application/json:
                schema:
                  type: array
                  items:
                      type: object
                      allOf:
                        - $ref: ../global/paginatedResponseDefinition.yml
                        - type: object
                          properties:
                            items:
                              type: array
                              items:
                                type: object
                                allOf:
                                  - $ref: ../global/autoGeneratedDataDefinition.yml
                                  - $ref: ./roleDefinition.yml
                example:
                  items:
                    - _id: cbe58c3c-9d86-466c-a8b4-1b26c379f276
                      createdAt: 2023-08-06T18:03:06.290Z
                      updatedAt: 2023-08-07T03:10:24.423Z
                      absoluteAuthority: false
                      description: Have access to most of the resources.
                      featuresRefs:
                          - 3f74c3a5-3200-4c9f-a5c7-077515e1e45b
                          - 03b2f7f8-119f-4a7b-a9ea-af732a90f56a
                          - c2b6d920-a101-45e5-bbdb-0f6a07da1f33
                      level: 1
                      name: Manager
                  page: 1
                  pageSize: 100
                  totalPages: 1
                  nextURL: null