type: object
required:
  - key
  - value
  - type
properties:
  key:
    type: string
  value:
    type: string
  type:
    type: string

example:
  key: default-workspace
  value: c54a858a-b095-4405-9a1c-8567ec91da5e
  type: string