const router = require('express').Router();

const {
    fetchLogs
} = require('./logs');

/**
 * @swagger
 * components:
 *      schemas:
 *          Log:
 *              type: object
 *              properties:
 *                  id:
 *                      type: string
 *                      description: autogenerated value
 *                  title:
 *                      type: string
 *                      description: the title information of the log
 *                  message:
 *                      type: string
 *                      description: the log explaination
 *                  creator:
 *                      type: string
 *                      description: service of account who created the log
 *                  createdAt:
 *                      type: string
 *                      description: date when this item was created
 *                  updatedAt:
 *                      type: string
 *                      description: date when this item was updated
 *              example:
 *                  id: db422ca5-b0a0-43b1-9381-417be994f10e
 *                  title: Authentication
 *                  message: login by bearer authentication
 *                  creator: Gilbert Cuerbo
 *                  createdAt: 2021-11-08T13:18:40.558Z
 *                  updatedAt: 2021-11-08T13:18:40.558Z
 */

/**
 * @swagger
 * tags:
 *      name: Logs
 *      description: API to manage logs
 */

/**
 * @swagger
 * /api/v1/logs:
 *      get:
 *          tags: [Logs]
 *          summary: Returns multiple logs in paginated manner
 *          parameters:
 *              - in: query
 *                name: pageSize
 *                schema:
 *                      type: number
 *                description: number of items per page 
 *              - in: query
 *                name: pageNumber
 *                schema:
 *                      type: number
 *                description: current page number
 *          responses:
 *              200:
 *                  description: object containing a list of logs
 *                  content:
 *                      application/json:
 *                          schema:
 *                              type: object
 *                              properties:
 *                                  data:
 *                                      type: object
 *                                      properties:
 *                                          next:
 *                                              type: string
 *                                              nullable: true
 *                                              description: url pointing to the next page
 *                                          pageSize:
 *                                              type: number
 *                                              description: number of items per page
 *                                          pageNumber:
 *                                              type: number
 *                                              description: the current page number
 *                                          totalPage:
 *                                              type: number
 *                                              description: all the availbale pages
 *                                          totalItems:
 *                                              type: number
 *                                              description: all items in all pages
 *                                          items:
 *                                              type: array
 *                                              items:
 *                                                  $ref: '#/components/schemas/Log'
 *              500:
 *                  description: Some error occured in the server
 *                  content:
 *                      application/json:
 *                          schema:
 *                              $ref: '#/components/schemas/Error'
 */
router.get('/logs', fetchLogs)

module.exports = router